// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAntDesignFlagOutlined: typeof import('~icons/ant-design/flag-outlined')['default']
    IAntDesignLikeFilled: typeof import('~icons/ant-design/like-filled')['default']
    IBiStarFill: typeof import('~icons/bi/star-fill')['default']
    IBxBxsCategoryAlt: typeof import('~icons/bx/bxs-category-alt')['default']
    IBxBxsMessageSquareEdit: typeof import('~icons/bx/bxs-message-square-edit')['default']
    IEosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    IEpFlag: typeof import('~icons/ep/flag')['default']
    IIcBaselineCheck: typeof import('~icons/ic/baseline-check')['default']
    IIcBaselineRemoveRedEye: typeof import('~icons/ic/baseline-remove-red-eye')['default']
    IIcBaselineTiktok: typeof import('~icons/ic/baseline-tiktok')['default']
    IIconoirChatBubble: typeof import('~icons/iconoir/chat-bubble')['default']
    IIcOutlineAlternateEmail: typeof import('~icons/ic/outline-alternate-email')['default']
    IIcRoundVpnKey: typeof import('~icons/ic/round-vpn-key')['default']
    IIcSharpSettings: typeof import('~icons/ic/sharp-settings')['default']
    IIonChatbubbleEllipses: typeof import('~icons/ion/chatbubble-ellipses')['default']
    IIonMdCheckmarkCircleOutline: typeof import('~icons/ion/md-checkmark-circle-outline')['default']
    IIonMdHome: typeof import('~icons/ion/md-home')['default']
    IJamTriangleDangerF: typeof import('~icons/jam/triangle-danger-f')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    IMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IMaterialSymbolsAddCircleRounded: typeof import('~icons/material-symbols/add-circle-rounded')['default']
    IMaterialSymbolsArrowCircleRight: typeof import('~icons/material-symbols/arrow-circle-right')['default']
    IMaterialSymbolsArrowForwardRounded: typeof import('~icons/material-symbols/arrow-forward-rounded')['default']
    IMaterialSymbolsBookmarkAdd: typeof import('~icons/material-symbols/bookmark-add')['default']
    IMaterialSymbolsBookmarkAddRounded: typeof import('~icons/material-symbols/bookmark-add-rounded')['default']
    IMaterialSymbolsCheckCircle: typeof import('~icons/material-symbols/check-circle')['default']
    IMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IMaterialSymbolsShare: typeof import('~icons/material-symbols/share')['default']
    IMdiClockOutline: typeof import('~icons/mdi/clock-outline')['default']
    IMdiClockTimeEightOutline: typeof import('~icons/mdi/clock-time-eight-outline')['default']
    IMdiDocument: typeof import('~icons/mdi/document')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiPencilCircle: typeof import('~icons/mdi/pencil-circle')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IOcticonIssueDraft16: typeof import('~icons/octicon/issue-draft16')['default']
    IPhLinkSimpleFill: typeof import('~icons/ph/link-simple-fill')['default']
    IPhPersonSimpleRunBold: typeof import('~icons/ph/person-simple-run-bold')['default']
    IRiCompass3Fill: typeof import('~icons/ri/compass3-fill')['default']
    IRiInstagramFill: typeof import('~icons/ri/instagram-fill')['default']
    IRiUser4Fill: typeof import('~icons/ri/user4-fill')['default']
    ISimpleIconsZalo: typeof import('~icons/simple-icons/zalo')['default']
    ITablerSearch: typeof import('~icons/tabler/search')['default']
    IUilFacebookF: typeof import('~icons/uil/facebook-f')['default']
  }
}
